meta_product_name: "PollingU"
meta_separator: "|"
meta_title: "Mạng xã hội xếp hạng nội dung"
meta_description: "Cập nhật các thông tin thời sự, giải trí,... mà bạn quan tâm đã được xếp hạng bởi cộng đồng người dùng"
meta_image: "favicon.ico"
meta_key_word: "Mạng xã hội, thông tin, thời sự, xếp hạng nội dung"
twitter_account: "@dungnguyen_93"   # required for Twitter Cards